const $=id=>document.getElementById(id);
const builtin=[
 {id:'builtin-browser',name:'Browser',category:'Utilities',description:'Explore the web from your console.',icon:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/assets/browser-icon.svg',path:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/browser/index.html'},
 {id:'builtin-spotify',name:'Spotify',category:'Music',description:'Your music. Wherever you play.',icon:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/assets/spotify-official.png',path:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/music/index.html'},
 {id:'builtin-youtube',name:'YouTube',category:'Entertainment',description:'Videos, music, and your favorite creators.',icon:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/assets/youtube-official.webp',path:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/youtube/index.html'},
 {id:'builtin-chat',name:'Chat',category:'Social',description:'Your people. One conversation away. Sign in to your Nocturne account to join the conversation.',icon:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/assets/chat-icon.png',path:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/messages/index.html'},
 {id:'builtin-movies',name:'Movies',category:'Entertainment',description:'Movies, series, and your watchlist.',icon:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/assets/netflix-icon.webp',path:'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/movie-proxy/library/index.html'}
].map(app=>({...app,builtin:true,author:'Console',version:'Included'}));
let apps=[],mine=[],user=null,view='Discover',category='',editing=null,icon='',toastTimer;
let installed=new Set();try{installed=new Set(JSON.parse(localStorage.getItem('store-installed')||'[]'));}catch{}
const token=()=>localStorage.getItem('noc-session')||'';
const api=async(path,options={})=>{const response=await fetch('/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/api/app-store'+path,{...options,headers:{'Content-Type':'application/json',...(token()?{'X-Noc-Session':token()}:{}),...options.headers}});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error||'Unable to load the App Store.'),{status:response.status});return data;};
function node(tag,text,cls){const element=document.createElement(tag);if(text!==undefined)element.textContent=text;if(cls)element.className=cls;return element;}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3000);}
function navigate(path){const url=new URL(path,location.origin),origin=new URLSearchParams(location.search).get('consoleOrigin');if(origin)url.searchParams.set('consoleOrigin',origin);location.href=url.href;}
function openApp(app){navigate(app.path||'/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/store/run.html?id='+encodeURIComponent(app.id));}
function notifyConsole(id,remove=false){const origin=window.CONSOLE_BRIDGE?.origin;if(origin)parent.postMessage({type:'gsn-store-install',id,remove},origin);}
function install(app){if(app.builtin||installed.has(app.id))return openApp(app);installed.add(app.id);localStorage.setItem('store-installed',JSON.stringify([...installed]));notifyConsole(app.id);toast(app.name+' added to Media');render();}
function image(app){const img=node('img',undefined,'app-icon'+(app.id==='builtin-youtube'?' youtube':''));img.src=app.icon;img.alt='';return img;}
function card(app){const row=node('article',undefined,'app-row'),info=node('button',undefined,'app-info'),text=node('span',undefined,'app-text');info.setAttribute('aria-label','View '+app.name);text.append(node('strong',app.name),node('small',app.category));info.append(image(app),text);info.onclick=()=>details(app);const get=node('button',app.builtin||installed.has(app.id)?'OPEN':'GET','get-button');get.setAttribute('aria-label',(get.textContent==='GET'?'Get ':'Open ')+app.name);get.onclick=()=>install(app);row.append(info,get);return row;}
function empty(title,subtitle){const box=node('div',undefined,'empty');box.append(node('strong',title),node('span',subtitle));return box;}
function drawList(target,list,emptyTitle='No apps found',emptyText='Try another search or category.'){target.replaceChildren(...(list.length?list.map(card):[empty(emptyTitle,emptyText)]));}
function render(){
 const query=$('search').value.trim().toLowerCase();const matches=app=>(!query||[app.name,app.description,app.category,app.author].some(x=>x.toLowerCase().includes(query)))&&(!category||app.category===category);
 const all=[...apps,...builtin];let list=view==='Your uploads'?mine:view==='Library'?all.filter(a=>a.builtin||installed.has(a.id)):view==='Games'?all.filter(a=>/games?/i.test(a.category)):view==='Apps'?all.filter(a=>!/games?/i.test(a.category)):all;
 $('heading').textContent=query?'Search':view;$('hero').hidden=view!=='Discover'||!!query;$('communitySection').hidden=view!=='Discover'||!!query;
 $('sectionTitle').textContent=query?'Search results':view==='Discover'?'Apps for every day':view==='Your uploads'?'Made by you':view==='Library'?'Your collection':view;
 $('sectionSubtitle').textContent=view==='Your uploads'?'Publish, update, and manage your apps.':view==='Library'?'Included apps and everything you’ve added.':'Find something you’ll love.';
 if(view==='Discover'&&!query)list=builtin;
 list=list.filter(matches);$('count').textContent=list.length+' apps';drawList($('apps'),list,view==='Your uploads'?(user?'Your first app starts here':'Sign in to see your uploads'):'No apps yet',view==='Your uploads'?'Choose Publish an app to get started.':'Be the first to share something in this category.');
 drawList($('community'),apps.filter(matches),'Be the first to publish','A useful tool, a little game, a big idea. Your app could be here.');
 $('categories').replaceChildren();if(['Categories','Apps','Games'].includes(view)||query){for(const name of ['All',...new Set(all.map(a=>a.category))]){const button=node('button',name,category===name||!category&&name==='All'?'active':'');button.onclick=()=>{category=name==='All'?'':name;render();};$('categories').append(button);}}
 document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===view));
}
async function load(){try{apps=(await api('/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps')).apps;$('status').textContent='';render();}catch(error){$('status').textContent=error.message;}}
async function account(){try{const result=await api('/me');user=result.user;mine=result.apps;$('accountName').textContent=user.name;$('authNotice').hidden=true;}catch{user=null;mine=[];$('accountName').textContent='Sign in with Chat';$('authNotice').hidden=false;}render();}
function details(app){
 const content=$('detailContent');content.replaceChildren();const top=node('div',undefined,'detail-top'),text=node('div'),get=node('button',app.builtin||installed.has(app.id)?'Open':'Get','blue-button');get.onclick=()=>{install(app);get.textContent='Open';};text.append(node('h2',app.name),node('p',app.author),get);top.append(image(app),text);
 const stats=node('div',undefined,'detail-stats');for(const [label,value]of [['Category',app.category],['Version',app.version],['Publisher',app.author]]){const item=node('div',label);item.append(node('strong',value));stats.append(item);}
 content.append(top,stats,node('h3','About this app'),node('p',app.description,'description'));
 const actions=node('div',undefined,'detail-actions');if(mine.some(a=>a.id===app.id)){const edit=node('button','Edit app','secondary');edit.onclick=()=>{ $('details').close();editApp(app);};const del=node('button','Delete app','secondary danger');del.onclick=async()=>{if(!confirm('Delete “'+app.name+'” from the store?'))return;try{await api('/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/'+app.id,{method:'DELETE'});$('details').close();await Promise.all([load(),account()]);toast('App deleted');}catch(e){toast(e.message);}};actions.append(edit,del);}
 if(!app.builtin&&installed.has(app.id)){const remove=node('button','Remove from Library','secondary');remove.onclick=()=>{installed.delete(app.id);localStorage.setItem('store-installed',JSON.stringify([...installed]));notifyConsole(app.id,true);$('details').close();render();};actions.append(remove);}content.append(actions);$('details').showModal();
}
async function editApp(app){
 $('publishForm').reset();editing=app?.id||null;icon='';$('iconPreview').src='/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/assets/app-store.svg';$('editorTitle').textContent=editing?'Update your app':'Publish your app';$('submitApp').textContent=editing?'Save changes':'Publish app';$('publishFeedback').textContent='';$('authNotice').hidden=!!user;
 if(app){try{const data=(await api('/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/'+app.id)).app;for(const key of ['name','category','description','version','code'])$('publishForm').elements[key].value=data[key];icon=data.icon;$('iconPreview').src=icon;}catch(error){return toast(error.message);}}
 $('editor').showModal();void account();
}
const read=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('That file could not be read.'));reader.readAsDataURL(file);});
$('iconFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>256*1024)throw Error('Choose a PNG, JPEG or WebP icon under 256 KB.');const data=await read(file),img=new Image();img.src=data;await img.decode();icon=data;$('iconPreview').src=icon;$('publishFeedback').textContent='';}catch(error){$('publishFeedback').textContent=error.message;}};
$('codeFile').onchange=async event=>{const file=event.target.files[0];if(!file)return;if(file.size>1024*1024){$('publishFeedback').textContent='Choose an HTML file under 1 MB.';return;}$('appCode').value=await file.text();};
$('publishForm').onsubmit=async event=>{event.preventDefault();const button=$('submitApp');button.disabled=true;$('publishFeedback').textContent='';try{if(!icon)throw Error('Choose an icon for your app.');const values=Object.fromEntries(new FormData(event.target));const result=await api('/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps'+(editing?'/'+editing:''),{method:editing?'PUT':'POST',body:JSON.stringify({...values,icon})});$('editor').close();await Promise.all([load(),account()]);toast(editing?'App updated':'Your app is live in this store');details(result.app);}catch(error){$('publishFeedback').textContent=error.message;if(error.status===401)$('authNotice').hidden=false;}finally{button.disabled=false;}};
$('previewButton').onclick=()=>{const code=$('appCode').value;if(!code.trim()){$('publishFeedback').textContent='Add your HTML code first.';return;}$('previewFrame').srcdoc=code;$('preview').showModal();};
$('preview').addEventListener('close',()=>$('previewFrame').removeAttribute('srcdoc'));
for(const dialog of document.querySelectorAll('dialog')){dialog.querySelector('.dialog-close').onclick=()=>dialog.close();dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});}
document.addEventListener('keydown',event=>{const open=[...document.querySelectorAll('dialog[open]')].pop();if(event.key==='Escape'&&open){event.preventDefault();event.stopImmediatePropagation();open.close();}},true);
for(const id of ['publish','headerPublish','heroPublish'])$(id).onclick=()=>editApp();
$('navigation').onclick=event=>{const button=event.target.closest('[data-view]');if(!button)return;view=button.dataset.view;category='';$('search').value='';render();if(view==='Your uploads')void account();};$('search').oninput=()=>{category='';render();};
for(const id of ['account','signInLink'])$(id).onclick=event=>{event.preventDefault();navigate('/gh/unblockedgames99x-code/gsn-console-cdn@v20260928-17/apps/messages/index.html');};
$('date').textContent=new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}).toUpperCase();render();void load();void account();
window.addEventListener('focus',()=>{void load();void account();});
