(()=>{'use strict';
 const TOKEN='cherri-session',users=new Map(),channels=new Map(),pending=new Map();let me=null,socket=null,room=null,reconnect=null,refresh=null;
 const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem('cherri:'+key))??fallback}catch{return fallback}};
 const save=(key,value)=>{try{localStorage.setItem('cherri:'+key,JSON.stringify(value))}catch{}};
 const token=()=>{try{return localStorage.getItem(TOKEN)||''}catch{return ''}};
 const asset=value=>{if(!value)return '';try{const u=new URL(value,'https://cherrion.top');return u.protocol==='https:'||/^data:image\/(png|jpeg|gif|webp);base64,/i.test(value)?u.href:''}catch{return ''}};
 function user(row={}){const id=String(row.id??row.fromUserId??row.userId??'');const previous=users.get(id)||{};const result={...previous,...row,id,username:row.username||previous.username||'Member',displayName:row.display||row.displayName||previous.displayName||row.username||'Member',avatar:asset(row.pfp??row.avatarUrl??row.avatar??previous.avatar),bio:row.bio??previous.bio??''};if(id){users.set(id,result);window.dispatchEvent(new CustomEvent('nocturne-profile',{detail:result}))}return result}
 async function request(path,body,method=body===undefined?'GET':'POST'){
  const headers={Accept:'application/json'};if(token())headers.Authorization='Bearer '+token();const form=body instanceof FormData;if(body!==undefined&&!form)headers['Content-Type']='application/json';
  const response=await fetch('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/console-cherri'+path.replace(/^\/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/,''),{method,headers,body:body===undefined?undefined:form?body:JSON.stringify(body),credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(30000)});
  const data=response.status===204?{}:await response.json().catch(()=>{throw new Error('The chat server returned an invalid response. Try again shortly.')});
  if(!response.ok||data?.ok===false)throw Object.assign(new Error(data.error||data.message||'This action could not be completed.'),{status:response.status});return data;
 }
 function close(){clearTimeout(reconnect);clearTimeout(refresh);socket?.close();socket=null;room=null}
 function listen(id){const name=id.replace(/^room:/,'');if(room===name&&socket)return;close();room=name;function connect(){if(!token()||room!==name)return;const ws=new WebSocket('wss://cherrion.top/api/chat/channels/'+encodeURIComponent(name)+'/stream?token='+encodeURIComponent(token()));socket=ws;ws.onmessage=()=>{clearTimeout(refresh);refresh=setTimeout(()=>window.dispatchEvent(new Event('nocturne-update')),60)};ws.onerror=()=>{};ws.onclose=()=>{if(socket===ws){socket=null;reconnect=setTimeout(connect,5000)}}}connect()}
 function message(row){const authorId=String(row.fromUserId??row.authorId??row.userId??'');if(row.username)user({id:authorId,username:row.username,avatarUrl:row.avatarUrl,display:row.display});const content=String(row.content??row.text??'');const image=asset(row.imageUrl||row.gifUrl||content.match(/https:\/\/[^\s<>]+\.(?:gif|webp)(?:[?#][^\s<>]*)?(?=\s|$)/i)?.[0]);return {id:String(row.id),authorId,text:image?content.replace(image,'').trim():content,createdAt:new Date(row.sentAt||row.createdAt||Date.now()).getTime(),editedAt:row.editedAt?new Date(row.editedAt).getTime():undefined,replyTo:row.replyToId?String(row.replyToId):null,reactions:Array.isArray(row.reactions)?row.reactions:[],attachments:image?[{type:'image/gif',url:image,name:row.gifId?'GIF':'Image'}]:[]}}
 async function api(path,options={}){const body=typeof options.body==='string'?JSON.parse(options.body):options.body||{},method=options.method||'GET';let match;
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/auth/me'){if(!token())throw Object.assign(new Error('Sign in to Chat.'),{status:401});const data=await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/auth/me');me=user(data.user||data);return {user:me}}
 if(/^\/api\/auth\/(login|register)$/.test(path)){const data=await request(path,{username:body.username,password:body.password});if(!data.token)throw new Error('Sign-in did not return a session.');localStorage.setItem(TOKEN,data.token);return api('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/auth/me')}
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/auth/logout'){try{await request(path,{})}finally{localStorage.removeItem(TOKEN);close();me=null}return {signedOut:true}}
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/members'){const data=await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/members');(Array.isArray(data)?data:data.members||[]).forEach(user);return {members:[...users.values()]}}
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/dm'&&method==='GET'){const data=await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/chat/channels');const list=(Array.isArray(data)?data:data.channels||[]).filter(c=>c.kind!=='voice').map(c=>{const id='room:'+c.name;const value={...c,id,name:c.name,kind:'server',backend:'neo',members:[],canPost:c.canPost!==false};channels.set(id,value);return value});return {channels:list}}
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/dm'&&method==='POST')throw new Error('Direct messages are not available on this server.');
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/friends'){const data=await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/friends');const list=[];for(const [key,state] of [['friends','friends'],['incoming','incoming'],['outgoing','outgoing']])for(const row of data[key]||[]){const person=user(row.user||row);list.push({id:String(row.id||person.id),state,user:person})}return {friends:list}}
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/friends/requests')return request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/friends/request',{username:body.username});
 if((match=path.match(/^\/api\/friends\/requests\/([^/]+)\/(accept|decline)$/)))return request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/friends/respond',{id:decodeURIComponent(match[1]),accept:match[2]==='accept'});
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/me/settings'){const key='settings:'+me.id,settings=read(key,{});if(method==='PATCH'){const profile=body.neoChatProfile;if(profile){let pfp=profile.kind==='photo'?profile.value:profile.kind==='tapback'?'https://raw.githubusercontent.com/Wimell/Tapback-Memojis/main/src/public/images/avatars/v1/'+(Number(profile.value)+1)+'.png':null;if(pfp){if(pfp.startsWith('data:')){const blob=await fetch(pfp).then(r=>r.blob());const form=new FormData();form.append('userId',me.id);form.append('file',blob,'avatar.png');form.append('focusX','0.5');form.append('focusY','0.5');form.append('zoom','1');pfp=(await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/users/upload-pfp',form)).pfpUrl}await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/users/settings',{pfp},'PATCH');me=user({...me,pfp})}}Object.assign(settings,body);save(key,settings)}return {settings}}
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/users/me'&&method==='PATCH'){await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/users/settings',{display:body.displayName},'PATCH');me=user({...me,display:body.displayName});return {user:me}}
 if(path==='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/unread')return {unread:read('read:'+me.id,{})};
 if((match=path.match(/^\/api\/channels\/([^/]+)\/read$/))){const reads=read('read:'+me.id,{});reads[decodeURIComponent(match[1])]=Date.now();save('read:'+me.id,reads);return {ok:true}}
 if((match=path.match(/^\/api\/channels\/([^/]+)\/messages$/))){const id=decodeURIComponent(match[1]),name=id.replace(/^room:/,''),route='/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/chat/channels/'+encodeURIComponent(name)+'/messages';if(method==='POST'){if(channels.get(id)?.canPost===false)throw new Error('This channel is read-only.');const payload={content:String(body.text||'')};if(body.replyTo)payload.replyToId=body.replyTo;const attachment=body.attachments?.[0];if(attachment){if(attachment.gifId)payload.gifId=attachment.gifId;else if(/^https:\/\//.test(attachment.url||attachment.data||''))payload.content=[payload.content,attachment.url||attachment.data].filter(Boolean).join('\n');else throw new Error('Choose a GIF from GIPHY. File attachments are not supported by this adapter.')}const row=await request(route,payload);if(!row.id&&!row.message?.id)throw new Error('The server did not confirm this message.');return {message:message(row.message||row)}}if(pending.has(id))return pending.get(id);const promise=request(route).then(data=>({messages:(Array.isArray(data)?data:data.messages||[]).map(message)})).finally(()=>pending.delete(id));pending.set(id,promise);return promise}
 if((match=path.match(/^\/api\/messages\/([^/]+)\/react$/))&&method==='POST')return request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/chat/messages/'+encodeURIComponent(decodeURIComponent(match[1]))+'/react',{emoji:body.emoji});
 if((match=path.match(/^\/api\/messages\/([^/]+)$/))){const data=await request('/gh/unblockedgames99x-code/gsn-console-cdn@v20260926-1/api/chat/messages/'+encodeURIComponent(decodeURIComponent(match[1])),method==='DELETE'?undefined:{content:body.text},method);return {message:message(data.message||{...data,id:decodeURIComponent(match[1]),content:body.text,fromUserId:me.id,editedAt:new Date().toISOString()})}}
 throw new Error('This action is not available.');}
 window.NEO_CHAT_BRIDGE={api,mode:'neo',active:true,subscribe:listen};window.CHERRI_CHAT={request,get me(){return me}};window.NOCTURNE_CHAT={get me(){return me},request(){throw new Error('Calls are not available on this server.')}};
 window.addEventListener('pagehide',close);
})();
