(()=>{'use strict';const $=id=>document.getElementById(id),key='cherri-ai-conversations-v1';let chats=[],current=null,pending=null;try{chats=JSON.parse(localStorage.getItem(key)||'[]').filter(c=>c.id&&Array.isArray(c.messages))}catch{}const md=window.markdownit({html:false,linkify:true,breaks:true});
function save(){try{localStorage.setItem(key,JSON.stringify(chats))}catch{showError('Browser storage is full. This conversation cannot be saved locally.')}}
function showError(message){$('error').textContent=message;$('error').hidden=!message}
function history(){const q=$('search').value.toLowerCase();$('history').replaceChildren();chats.filter(c=>c.title.toLowerCase().includes(q)).forEach(c=>{const row=document.createElement('div');row.className='history-row'+(current?.id===c.id?' active':'');const btn=document.createElement('button');btn.textContent=c.title;btn.onclick=()=>{cancel();current=c;render();history();if(innerWidth<700)document.body.classList.add('sidebar-hidden')};const del=document.createElement('button');del.className='delete';del.textContent='×';del.setAttribute('aria-label','Delete '+c.title);del.onclick=()=>{if(current===c){cancel();current=null;render()}chats=chats.filter(x=>x!==c);save();history()};row.append(btn,del);$('history').append(row)})}
function render(){const list=current?.messages||[];$('welcome').hidden=!!list.length;$('thread').replaceChildren();for(const m of list){const article=document.createElement('article');article.className='message '+m.role;if(m.role==='user')article.textContent=m.content;else{const content=document.createElement('div');content.innerHTML=md.render(m.content);content.querySelectorAll('a').forEach(a=>{a.target='_blank';a.rel='noopener noreferrer'});const copy=document.createElement('button');copy.className='copy';copy.textContent='Copy';copy.onclick=()=>navigator.clipboard.writeText(m.content).then(()=>{copy.textContent='Copied'},()=>{copy.textContent='Copy unavailable'});article.append(content,copy)}$('thread').append(article)}$('thread').scrollTop=$('thread').scrollHeight}
function usage(data){if(Number.isFinite(data?.remaining))$('usage').textContent=data.remaining+' requests remaining today · Daily limit '+data.limit}
function headers(){const h={'Content-Type':'application/json'};try{const token=localStorage.getItem('cherri-session');if(token)h.Authorization='Bearer '+token}catch{}return h}
function busy(value){$('send').hidden=value;$('stop').hidden=!value;$('prompt').disabled=false}
function cancel(){pending?.abort();pending=null;busy(false);document.querySelector('.pending')?.remove()}
function fresh(){cancel();current=null;showError('');render();history();$('prompt').focus()}
async function send(event){event.preventDefault();const text=$('prompt').value.trim();if(!text||pending)return;showError('');if(!current){current={id:crypto.randomUUID(),title:text.slice(0,48),messages:[]};chats.unshift(current)}const conversation=current;const messages=[...conversation.messages,{role:'user',content:text}];conversation.messages=messages;save();history();render();$('prompt').value='';$('prompt').style.height='auto';const indicator=document.createElement('div');indicator.className='message pending';indicator.innerHTML='<div class="thinking" aria-label="Thinking"></div>';$('thread').append(indicator);$('thread').scrollTop=$('thread').scrollHeight;const controller=new AbortController();pending=controller;busy(true);try{const response=await fetch('/gh/unblockedgames99x-code/gsn-console-cdn@v20260927-28/api/console-services/ai/chat',{method:'POST',headers:headers(),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(150000)]),body:JSON.stringify({model:'dynamic/primary',messages})});const data=await response.json();usage(data.usage);if(!response.ok)throw new Error(data.error||data.message||'The AI service is unavailable.');if(typeof data.content!=='string'||!data.content)throw new Error('The provider returned an empty response. Please try again.');conversation.messages.push({role:'assistant',content:data.content});save();if(current===conversation)render()}catch(error){if(!controller.signal.aborted&&current===conversation){showError(error.name==='TimeoutError'?'The provider took too long. Try again shortly.':error.message);$('prompt').value=text;conversation.messages=conversation.messages.filter(m=>m!==messages.at(-1));save();render()}}finally{indicator.remove();if(pending===controller){pending=null;busy(false)}}}
$('composer').addEventListener('submit',send);$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('composer').requestSubmit()}});$('prompt').addEventListener('input',()=>{$('prompt').style.height='auto';$('prompt').style.height=Math.min(200,$('prompt').scrollHeight)+'px'});$('stop').onclick=cancel;$('newChat').onclick=fresh;$('freshChat').onclick=fresh;$('search').oninput=history;$('hideSidebar').onclick=()=>document.body.classList.add('sidebar-hidden');$('showSidebar').onclick=()=>document.body.classList.remove('sidebar-hidden');document.querySelectorAll('.suggestions button').forEach(b=>b.onclick=()=>{$('prompt').value=b.textContent;$('prompt').focus()});if(innerWidth<700)document.body.classList.add('sidebar-hidden');history();render();fetch('/gh/unblockedgames99x-code/gsn-console-cdn@v20260927-28/api/console-services/ai/usage',{headers:headers()}).then(r=>r.ok?r.json():null).then(usage).catch(()=>{});window.addEventListener('pagehide',cancel);
})();
