import {password,base64,hash,color,lorem} from './core.js';
const $=id=>document.getElementById(id);
const icons={lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',binary:'<path d="M7 4v6m-2 0h4M15 4h4v6h-4zM5 14h4v6H5zM17 14v6m-2 0h4"/>',hash:'<path d="M9 3 7 21M17 3l-2 18M4 9h17M3 15h17"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5z"/>',code:'<path d="m7 7-5 5 5 5m10-10 5 5-5 5m-4-12-2 18"/>',link:'<path d="M10 7H7a5 5 0 0 0 0 10h3m4-10h3a5 5 0 0 1 0 10h-3M8 12h8"/>',color:'<circle cx="12" cy="12" r="9"/><path d="M12 3v18M3 12h18"/>',text:'<path d="M6 3h8l4 4v14H6zM14 3v5h4M9 12h6m-6 4h6"/>'};
const input=(label,name,value,type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${value}" ${extra}></label>`;
const select=(label,name,options)=>`<label class="field"><span>${label}</span><select name="${name}">${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>`;
const text=label=>`<label class="field"><span>${label}</span><textarea name="input" rows="5" spellcheck="false" maxlength="1000000"></textarea></label>`;
const mode=()=>select('Operation','mode',[['encode','Encode'],['decode','Decode']]);
const tools=[
 {id:'password',name:'Password Generator',description:'Generate secure random passwords',category:'Generators',icon:'lock',action:'Generate password',fields:()=>input('Password length','length','20','number','min="4" max="256" required')+[['upper','Uppercase (A–Z)'],['lower','Lowercase (a–z)'],['numbers','Numbers (0–9)'],['symbols','Symbols (!@#$…)']].map(([id,label])=>`<label class="check"><input name="${id}" type="checkbox" checked>${label}</label>`).join(''),run:f=>password(+f.get('length'),[['upper','ABCDEFGHIJKLMNOPQRSTUVWXYZ'],['lower','abcdefghijklmnopqrstuvwxyz'],['numbers','0123456789'],['symbols','!@#$%^&*()-_=+[]{};:,.?']].filter(([name])=>f.has(name)).map(([,chars])=>chars))},
 {id:'base64',name:'Base64 Encode/Decode',description:'Encode or decode Base64 strings',category:'Encoders',icon:'binary',action:'Convert',fields:()=>mode()+text('Text or Base64'),run:f=>base64(f.get('input'),f.get('mode')==='decode')},
 {id:'hash',name:'Hash Generator',description:'Generate MD5, SHA-1, SHA-256 hashes',category:'Generators',icon:'hash',action:'Generate hash',fields:()=>select('Algorithm','algorithm',[['SHA-256','SHA-256'],['SHA-1','SHA-1'],['MD5','MD5']])+text('Text to hash'),run:f=>hash(f.get('input'),f.get('algorithm'))},
 {id:'uuid',name:'UUID Generator',description:'Generate random UUIDs/GUIDs',category:'Generators',icon:'spark',action:'Generate UUIDs',fields:()=>input('Number of UUIDs','count','1','number','min="1" max="100" required'),run:f=>{const n=+f.get('count');if(!Number.isInteger(n)||n<1||n>100)throw Error('Choose 1 to 100 UUIDs.');return Array.from({length:n},()=>crypto.randomUUID()).join('\n');}},
 {id:'json',name:'JSON Formatter',description:'Format and validate JSON',category:'Utilities',icon:'code',action:'Format JSON',fields:()=>select('Formatting','spacing',[['2','2 spaces'],['4','4 spaces'],['0','Minify']])+text('JSON'),run:f=>{try{return JSON.stringify(JSON.parse(f.get('input')),null,+f.get('spacing'));}catch(e){throw Error('Invalid JSON: '+e.message);}}},
 {id:'url',name:'URL Encode/Decode',description:'Encode or decode URL strings',category:'Encoders',icon:'link',action:'Convert',fields:()=>mode()+select('Encoding type','type',[['component','URL component (query value)'],['url','Full URL (preserve separators)']])+text('Text or URL'),run:f=>{try{return(f.get('mode')==='encode'?(f.get('type')==='url'?encodeURI:encodeURIComponent):(f.get('type')==='url'?decodeURI:decodeURIComponent))(f.get('input'));}catch{throw Error('Enter valid text or a correctly percent-encoded URL.');}}},
 {id:'color',name:'Color Converter',description:'Convert between color formats',category:'Converters',icon:'color',action:'Convert color',fields:()=>input('HEX, RGB, or HSL color','input','#8fbfff')+'<div id="swatch" class="swatch" aria-label="Color preview"></div>',run:f=>{const result=color(f.get('input'));$('swatch').style.backgroundColor=result.hex;return result.text;}},
 {id:'lorem',name:'Lorem Ipsum Generator',description:'Generate placeholder text',category:'Generators',icon:'text',action:'Generate text',fields:()=>select('Generate','unit',[['paragraphs','Paragraphs'],['sentences','Sentences'],['words','Words']])+input('Count','count','3','number','min="1" max="100" required'),run:f=>lorem(+f.get('count'),f.get('unit'))}
];
let active,op=0,opener;
function render(category){$('grid').replaceChildren();for(const tool of tools.filter(t=>category==='All'||t.category===category)){const button=document.createElement('button');button.className='card';button.innerHTML=`<span class="tool-icon" aria-hidden="true"><svg viewBox="0 0 24 24">${icons[tool.icon]}</svg></span><strong>${tool.name}</strong><small>${tool.description}</small>`;button.addEventListener('click',()=>open(tool,button));$('grid').append(button);}}
for(const category of ['All','Generators','Encoders','Converters','Utilities']){const button=document.createElement('button');button.textContent=category;button.setAttribute('aria-pressed',String(category==='All'));button.onclick=()=>{for(const b of $('categories').children)b.setAttribute('aria-pressed',String(b===button));render(category);};$('categories').append(button);}
function open(tool,button){active=tool;opener=button;op++;$('toolTitle').textContent=tool.name;$('toolCategory').textContent=tool.category;$('toolDescription').textContent=tool.description;$('fields').innerHTML=tool.fields();$('result').value='';$('error').textContent='';$('status').textContent='';$('run').textContent=tool.action;$('run').disabled=false;$('copy').disabled=true;$('editor').showModal();}
$('close').onclick=()=>$('editor').close();$('editor').addEventListener('close',()=>{op++;opener?.focus();});
$('toolForm').addEventListener('submit',async event=>{event.preventDefault();const job=++op;$('error').textContent='';$('status').textContent='';$('result').value='';$('copy').disabled=true;$('run').disabled=true;try{const result=await active.run(new FormData(event.currentTarget));if(job!==op)return;$('result').value=result;$('copy').disabled=false;$('status').textContent='Done';}catch(error){if(job===op)$('error').textContent=error.message;}finally{if(job===op)$('run').disabled=false;}});
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('result').value);$('status').textContent='Copied';}catch{$('result').focus();$('result').select();$('status').textContent='Press Ctrl+C to copy the selected result.';}};
render('All');
